import { jsPDF } from 'jspdf';
import { StartupProject } from '../types';

export function downloadProjectPDF(project: StartupProject, type: 'exec' | 'market' | 'competitor' | 'financials' | 'pitch' | 'package') {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text(project.name.toUpperCase(), 15, 18);

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text(`${project.tagline} | ${project.stage} Stage | Ask: $${project.fundingGoal.toLocaleString()} ${project.currency}`, 15, 26);
  doc.text(`Generated by FundPilot AI • ${new Date().toLocaleDateString()}`, pageWidth - 15, 26, { align: 'right' });

  y = 45;
  doc.setTextColor(15, 23, 42);

  if (type === 'exec' || type === 'package') {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('1. Executive Summary', 15, y);
    y += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const overviewLines = doc.splitTextToSize(project.executiveSummary?.overview || project.problem, pageWidth - 30);
    doc.text(overviewLines, 15, y);
    y += overviewLines.length * 5 + 6;

    if (project.executiveSummary?.problemValidation) {
      doc.setFont('helvetica', 'bold');
      doc.text('Problem & Validation:', 15, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      const probLines = doc.splitTextToSize(`Severity: ${project.executiveSummary.problemValidation.painPointSeverity} | Market Impact: ${project.executiveSummary.problemValidation.affectedMarketSize}\n${project.executiveSummary.problemValidation.description}`, pageWidth - 30);
      doc.text(probLines, 15, y);
      y += probLines.length * 5 + 6;
    }

    if (project.executiveSummary?.uniqueValueProposition) {
      doc.setFont('helvetica', 'bold');
      doc.text('Unique Value Proposition:', 15, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.text(project.executiveSummary.uniqueValueProposition, 15, y);
      y += 10;
    }
  }

  if (type === 'market' || type === 'package') {
    if (y > 230) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('2. Market Opportunity Analysis', 15, y);
    y += 8;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(`TAM: ${project.marketResearch?.tamFormatted || '$15B'} | SAM: ${project.marketResearch?.samFormatted || '$3.5B'} | SOM: ${project.marketResearch?.somFormatted || '$250M'}`, 15, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Annual Growth Rate (CAGR): ${project.marketResearch?.cagr || 18.5}%`, 15, y);
    y += 8;

    if (project.marketResearch?.marketTrends) {
      doc.setFont('helvetica', 'bold');
      doc.text('Key Market Trends:', 15, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      project.marketResearch.marketTrends.forEach(trend => {
        doc.text(`• ${trend}`, 20, y);
        y += 5;
      });
      y += 5;
    }
  }

  if (type === 'competitor' || type === 'package') {
    if (y > 230) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('3. Competitor Intelligence & Differentiators', 15, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    if (project.competitors?.competitors) {
      project.competitors.competitors.forEach(comp => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${comp.name} (${comp.fundingRaised} raised, Val: ${comp.estimatedValuation})`, 15, y);
        y += 5;
        doc.setFont('helvetica', 'normal');
        doc.text(`Strengths: ${comp.strengths.join(', ')}`, 20, y);
        y += 5;
        doc.text(`Weaknesses: ${comp.weaknesses.join(', ')}`, 20, y);
        y += 7;
      });
    }
  }

  if (type === 'financials' || type === 'package') {
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('4. 3-Year Financial Model Projections', 15, y);
    y += 8;

    doc.setFontSize(10);
    doc.text(`Runway: ${project.financialModel?.runwayMonths || 14} Months | Break-Even: Month ${project.financialModel?.breakEvenMonth || 21}`, 15, y);
    y += 8;

    if (project.financialModel?.projections) {
      doc.setFont('helvetica', 'bold');
      doc.text('Year\tRevenue\tGross Profit\tNet Income\tEnding Cash', 15, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      project.financialModel.projections.forEach(p => {
        doc.text(`Year ${p.year}\t$${(p.revenue/1000).toFixed(0)}k\t$${(p.grossProfit/1000).toFixed(0)}k\t$${(p.netIncome/1000).toFixed(0)}k\t$${(p.endingCashBalance/1000).toFixed(0)}k`, 15, y);
        y += 6;
      });
      y += 6;
    }
  }

  if (type === 'pitch' || type === 'package') {
    if (y > 200) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text('5. 12-Slide Pitch Deck Summary', 15, y);
    y += 8;

    if (project.pitchDeck?.slides) {
      project.pitchDeck.slides.forEach(slide => {
        if (y > 260) { doc.addPage(); y = 20; }
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.text(`Slide ${slide.id}: ${slide.title}`, 15, y);
        y += 5;
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.text(`Highlight: ${slide.keyHighlight || slide.subtitle}`, 20, y);
        y += 5;
        slide.bullets.forEach(b => {
          doc.text(`- ${b}`, 25, y);
          y += 4;
        });
        y += 4;
      });
    }
  }

  // Save the generated document
  const filename = `${project.name.toLowerCase().replace(/\s+/g, '_')}_${type}_report.pdf`;
  doc.save(filename);
}
